Multilingual
dh-center/st-retrospect-api pull request #52
Opened 2020-02-10 22:33 UTC by Panda0412

2020-02-10 22:37 UTC, nikmel2803 requested changes

2020-02-10 22:37 UTC, nikmel2803 commented on src/directives/multilingual.ts
> + * Directive to filter the language
```suggestion
 * Directive for picking only necessary language from multilingual fields
```

2020-02-10 22:37 UTC, nikmel2803 commented on src/index.ts
> +import multilingual from "./directives/multilingual";
этот импорт уже есть выше

2020-02-10 22:37 UTC, nikmel2803 commented on src/resolvers/persons.ts
> +    // persons.map((person) => {
верни плз как было пока

2020-02-10 22:37 UTC, nikmel2803 commented on src/typeDefs/index.ts
> +  Directive to filter the language
```suggestion
  Directive for picking only necessary language from multilingual fields
```

2020-02-10 22:37 UTC, nikmel2803 commented on src/typeDefs/relations.ts
> +    synonyms: [JSON] @multilingual
```suggestion
    synonyms: [String] @multilingual
```

2020-02-10 22:48 UTC, nikmel2803 approved these changes

2020-02-11 10:02 UTC, ilyamore88 commented on src/directives/multilingual.ts
> +import { type } from 'os';
Лишнее

2020-02-11 10:02 UTC, ilyamore88 commented on src/typeDefs/index.ts
> +  """
```suggestion
  
  """
```

2020-02-11 10:02 UTC, ilyamore88 commented on src/typeDefs/index.ts
>    """
```suggestion
  
  """
```

2020-02-11 20:08 UTC, ilyamore88 approved these changes

2020-02-11 20:11 UTC, merged